### PR TITLE
Consolidation

### PR DESCRIPTION
**Pull request by mattjw79**
Consolidated the users and changeRequests to reduce code complexity and repetition.

### CODE REVIEW

**Comment by mattjw79** [comment]
This "shouldn't" change the way things work and any tests should continue to work. However, @lucasreed, I did rename the APIResponseJSON object to APIResponse and I think you were using that in your tests.

**Comment by lucasreed** [comment]
Heh, yep all tests are broken even after fixing APIResponse and InsertUser to InsertItem (datasource function). I'll work on getting them back to a good state before accepting this.

**Comment by lucasreed** [comment]
Well that was way easier to fix than I thought, I didn't have the `Content-Type: application/json` set on my call to api/authenticate in my tests. Looking good now.

**Review by lucasreed — COMMENTED** [review]
I'm still not sure I like the idea of anything after `/api/` working as a successful call. If I'm authenticated and pass my proper authorization header to GET `/api/animals` for example, I get back this:

```
{"success":true,"message":"success","data":[]}
```

I think the "success" parts of that message are misleading.

I understand that it's nice to make the API extensible but I think we have to come up with a better way than making everything register as a success with no data.

That's just my opinion, and I would still be ok merging this if we can work on a way to give a better response to a non-existing endpoint.

**Comment by lucasreed** [comment]
@mattjw79 How about we go ahead and merge this? That way I can rebase my testing branch and push that up as well. We can discuss/alter the restrictions on API routes later. Sound good?

**Comment by mattjw79** [comment]
Yeah, that would be fine. Sorry for the delay... I've been a bit preoccupied this weekend.

**Pull request merged**
